### ISSUE TITLE
[BUG] NameError: name 'resource' is not defined; missing dependencies

### ISSUE THREAD

**Issue by cuniculus-0** [Zipfian-Science/rickled#67]
**Describe the bug**

After a clean install and trying to use the CLI, the following error occurs due to missing dependencies:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\-------\.virtualenvs\test_installs-jItMaX31\Scripts\rickle.EXE\__main__.py", line 4, in <module>
  File "C:\Users\-------\.virtualenvs\test_installs-jItMaX31\Lib\site-packages\rickled\cli.py", line 11, in <module>
    from rickled.net import serve_rickle_http, serve_rickle_https
  File "C:\Users\-------\.virtualenvs\test_installs-jItMaX31\Lib\site-packages\rickled\net.py", line 25, in <module>
    class HttpResource(resource.Resource):
                       ^^^^^^^^
NameError: name 'resource' is not defined
```

**To Reproduce**
1. install in clean env.
2. use rickle as cli tool

**Expected behavior**

No exception..

**Comment by cuniculus-zipf** [comment]
done
