### ISSUE TITLE
[BUG] Error when using CLI and no tool is used

### ISSUE THREAD

**Issue by cuniculus-0** [Zipfian-Science/rickled#69]
**Describe the bug**

When running CLI tool and not specifiying options/commands:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\------\.virtualenvs\test_installs-jItMaX31\Scripts\rickle.EXE\__main__.py", line 7, in <module>
  File "C:\Users\------\.virtualenvs\test_installs-jItMaX31\Lib\site-packages\rickled\cli.py", line 515, in main
    args.func(args)
    ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by cuniculus-zipf** [comment]
done
